# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер лічильника')),
            ],
        ),
        migrations.CreateModel(
            name='ElObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Назва електрифікованого об'єкту")),
                ('address', models.CharField(max_length=255, verbose_name="Адреса електрифікованого об'єкту")),
            ],
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='el_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.ElObject'),
        ),
    ]
