# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_readings', models.PositiveIntegerField(verbose_name='Попередні покази лічильника')),
                ('current_readings', models.PositiveIntegerField(verbose_name='Поточні покази лічильника')),
                ('electricity_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.ElectricityMeter')),
            ],
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarrif_limit_1', models.FloatField()),
                ('tarrif_limit_2', models.FloatField()),
                ('tarrif_limit_3', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ElObject',
            new_name='ElectrifiedObject',
        ),
    ]
