# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20161121_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrifiedobject',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name="Адреса електрифікованого об'єкту"),
        ),
    ]
