# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20161121_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeter',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Номер лічильника'),
        ),
    ]
