# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculation', '0005_tariffs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrifiedobject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electrifiedobject',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адреса електрифікованого об'єкту"),
        ),
    ]
