# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculation', '0007_electrifiedobject_last_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='electrifiedobject',
            name='last_selected',
        ),
        migrations.AddField(
            model_name='lastselected',
            name='el_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculation.ElectrifiedObject'),
        ),
        migrations.AddField(
            model_name='lastselected',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
