# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_auto_20161123_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrifiedobject',
            name='last_selected_el_mtr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Останній обраний об'єкт"),
        ),
    ]
