# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0009_electrifiedobject_last_selected_el_mtr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrifiedobject',
            name='last_selected_el_mtr',
        ),
        migrations.AddField(
            model_name='lastselected',
            name='el_mtr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.ElectricityMeter'),
        ),
    ]
