# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер лічильника')),
            ],
        ),
        migrations.CreateModel(
            name='ElectrifiedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Назва електрифікованого об'єкту")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name="Адреса електрифікованого об'єкту")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LastSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_mtr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='electrified_objects.ElectricityMeter')),
                ('el_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electrified_objects.ElectrifiedObject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_readings', models.DateField(null=True)),
                ('previous_readings', models.PositiveIntegerField(null=True)),
                ('current_readings', models.PositiveIntegerField(null=True)),
                ('consumed', models.PositiveIntegerField(null=True)),
                ('electricity_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrified_objects.ElectricityMeter')),
            ],
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='el_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electrified_objects.ElectrifiedObject'),
        ),
    ]
