# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrified_objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffs',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tariffs',
        ),
    ]
